// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG8qetf4IcmmY7C47nFtkV6pwU176LR4E',
    appId: '1:345557853376:web:61b313849ea3c455e53925',
    messagingSenderId: '345557853376',
    projectId: 'uninet-44f4c',
    authDomain: 'uninet-44f4c.firebaseapp.com',
    storageBucket: 'uninet-44f4c.appspot.com',
    measurementId: 'G-49M8X02DVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8BOEUpboUB9_DUoLvd4ltDNAWk-3ymIw',
    appId: '1:345557853376:android:6f2f8f8fffe613d0e53925',
    messagingSenderId: '345557853376',
    projectId: 'uninet-44f4c',
    storageBucket: 'uninet-44f4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXG_Z5tWT5sKmD_20rFfqiGfN6x-WIriA',
    appId: '1:345557853376:ios:6e8471220d92274be53925',
    messagingSenderId: '345557853376',
    projectId: 'uninet-44f4c',
    storageBucket: 'uninet-44f4c.appspot.com',
    iosBundleId: 'com.example.uninet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXG_Z5tWT5sKmD_20rFfqiGfN6x-WIriA',
    appId: '1:345557853376:ios:6e8471220d92274be53925',
    messagingSenderId: '345557853376',
    projectId: 'uninet-44f4c',
    storageBucket: 'uninet-44f4c.appspot.com',
    iosBundleId: 'com.example.uninet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG8qetf4IcmmY7C47nFtkV6pwU176LR4E',
    appId: '1:345557853376:web:5c947bd3d46e76bae53925',
    messagingSenderId: '345557853376',
    projectId: 'uninet-44f4c',
    authDomain: 'uninet-44f4c.firebaseapp.com',
    storageBucket: 'uninet-44f4c.appspot.com',
    measurementId: 'G-2RRFETHBNB',
  );
}
